# Generated by Django 5.0.1 on 2025-05-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('VIP', 'VIP'), ('STAFF', 'Staff'), ('SUPERADMIN', 'Superadministrador')], default='CLIENT', max_length=15),
        ),
    ]
