# Generated by Django 5.0.1 on 2025-05-07 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('LIGHT', 'Light Jet'), ('MIDSIZE', 'Midsize Jet'), ('SUPER_MIDSIZE', 'Super Midsize Jet'), ('HEAVY', 'Heavy Jet'), ('ULTRA', 'Ultra Long Range'), ('VIP', 'VIP Airliner')], max_length=20)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('year_manufactured', models.IntegerField()),
                ('passenger_capacity', models.IntegerField()),
                ('range_nm', models.IntegerField(help_text='Range in nautical miles')),
                ('cruise_speed_kts', models.IntegerField(help_text='Cruise speed in knots')),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_phone', models.BooleanField(default=False)),
                ('has_entertainment', models.BooleanField(default=False)),
                ('has_meeting_room', models.BooleanField(default=False)),
                ('has_bedroom', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='aircraft/')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='aircraft/floorplans/')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_hours', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('maintenance_status', models.CharField(default='Available', max_length=50)),
                ('current_location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('departure_location', models.CharField(max_length=100)),
                ('arrival_location', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('passenger_count', models.IntegerField()),
                ('passenger_manifest', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('flight_duration', models.DurationField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_services_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_plan', models.TextField(blank=True)),
                ('catering_requirements', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('weather_briefing', models.TextField(blank=True)),
                ('flight_conditions', models.CharField(blank=True, max_length=50)),
                ('pilot_names', models.JSONField(default=list)),
                ('cabin_crew_names', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.aircraft')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
