# Generated by Django 5.0.1 on 2025-05-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('BOG', 'Bogotá'), ('MEX', 'Ciudad de México'), ('JFK', 'Nueva York'), ('LAX', 'Los Ángeles'), ('MAD', 'Madrid')], max_length=3)),
                ('destination', models.CharField(choices=[('BOG', 'Bogotá'), ('MEX', 'Ciudad de México'), ('JFK', 'Nueva York'), ('LAX', 'Los Ángeles'), ('MAD', 'Madrid')], max_length=3)),
                ('airline', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('stops', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('services', models.TextField(help_text='Servicios incluidos, separados por comas')),
            ],
        ),
    ]
