# Generated by Django 5.0.1 on 2025-05-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_commercialflight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialflight',
            name='price',
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen representativa del vuelo', null=True, upload_to='flights/'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='price_business',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='price_economy',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='price_first',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='stop_details',
            field=models.TextField(blank=True, help_text='Detalles de las escalas, separados por comas'),
        ),
    ]
