# Generated by Django 5.0.1 on 2025-05-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_commercialflight_price_commercialflight_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialflight',
            name='has_entertainment',
            field=models.BooleanField(default=False, help_text='Entretenimiento a bordo disponible'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='has_luxury_seating',
            field=models.BooleanField(default=False, help_text='Asientos de lujo disponibles'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='has_meals',
            field=models.BooleanField(default=False, help_text='Comidas incluidas'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='has_power_outlets',
            field=models.BooleanField(default=False, help_text='Tomas de corriente disponibles'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='has_wifi',
            field=models.BooleanField(default=False, help_text='Wi-Fi disponible a bordo'),
        ),
    ]
