# Generated by Django 5.0.1 on 2025-05-18 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_commercialflight_has_entertainment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Económica'), ('BUSINESS', 'Ejecutiva'), ('FIRST', 'Primera Clase')], max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('OCCUPIED', 'Ocupado')], default='AVAILABLE', max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.commercialflight')),
            ],
        ),
    ]
