# Generated by Django 5.0.1 on 2025-05-18 07:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_seat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialflight',
            options={'ordering': ['departure_time'], 'verbose_name': 'Vuelo comercial', 'verbose_name_plural': 'Vuelos comerciales'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_row', 'seat_column'], 'verbose_name': 'Asiento', 'verbose_name_plural': 'Asientos'},
        ),
        migrations.RemoveField(
            model_name='commercialflight',
            name='has_luxury_seating',
        ),
        migrations.RemoveField(
            model_name='commercialflight',
            name='has_meals',
        ),
        migrations.RemoveField(
            model_name='commercialflight',
            name='image',
        ),
        migrations.RemoveField(
            model_name='commercialflight',
            name='services',
        ),
        migrations.RemoveField(
            model_name='commercialflight',
            name='stop_details',
        ),
        migrations.RemoveField(
            model_name='commercialflight',
            name='stops',
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='aircraft_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de aeronave'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='airline_logo',
            field=models.ImageField(blank=True, null=True, upload_to='airline_logos/', verbose_name='Logo de aerolínea'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='destination_code',
            field=models.CharField(default='', max_length=3, verbose_name='Código IATA destino'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID externo'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='flight_number',
            field=models.CharField(default=123, max_length=10, verbose_name='Número de vuelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='has_complimentary_meal',
            field=models.BooleanField(default=False, verbose_name='Comida incluida'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='has_stops',
            field=models.BooleanField(default=False, verbose_name='Tiene escalas'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='origin_code',
            field=models.CharField(default='', max_length=3, verbose_name='Código IATA origen'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='price_premium_economy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio clase económica premium'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='source_api',
            field=models.CharField(blank=True, max_length=50, verbose_name='API de origen'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Programado'), ('DELAYED', 'Retrasado'), ('BOARDING', 'Abordando'), ('IN_AIR', 'En vuelo'), ('LANDED', 'Aterrizado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='stops_count',
            field=models.IntegerField(default=0, verbose_name='Número de escalas'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='stops_detail',
            field=models.JSONField(blank=True, default=list, verbose_name='Detalles de escalas'),
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='seat',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio adicional'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_column',
            field=models.CharField(default=1, max_length=1, verbose_name='Columna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_row',
            field=models.IntegerField(default=1, verbose_name='Fila'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('STANDARD', 'Estándar'), ('EXIT_ROW', 'Fila de salida'), ('EXTRA_LEGROOM', 'Espacio adicional'), ('PREFERRED', 'Preferente'), ('WINDOW', 'Ventana'), ('MIDDLE', 'Centro'), ('AISLE', 'Pasillo')], default='STANDARD', max_length=20, verbose_name='Tipo de asiento'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='airline',
            field=models.CharField(max_length=100, verbose_name='Aerolínea'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Fecha y hora de llegada'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Fecha y hora de salida'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='destination',
            field=models.CharField(default='', max_length=100, verbose_name='Aeropuerto de destino'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='duration',
            field=models.DurationField(verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='has_entertainment',
            field=models.BooleanField(default=False, verbose_name='Entretenimiento a bordo'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='has_power_outlets',
            field=models.BooleanField(default=False, verbose_name='Enchufes eléctricos'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi a bordo'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='origin',
            field=models.CharField(default='', max_length=100, verbose_name='Aeropuerto de origen'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='price_business',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio clase negocios'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='price_economy',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio clase económica'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='price_first',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio primera clase'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='cabin_class',
            field=models.CharField(choices=[('ECONOMY', 'Económica'), ('PREMIUM_ECONOMY', 'Económica Premium'), ('BUSINESS', 'Negocios'), ('FIRST', 'Primera')], default='ECONOMY', max_length=20, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10, verbose_name='Número de asiento'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('OCCUPIED', 'Ocupado'), ('BLOCKED', 'Bloqueado')], default='AVAILABLE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('flight', 'seat_number')},
        ),
        migrations.CreateModel(
            name='CommercialBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=10, unique=True, verbose_name='Código de reserva')),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Económica'), ('PREMIUM_ECONOMY', 'Económica Premium'), ('BUSINESS', 'Negocios'), ('FIRST', 'Primera')], default='ECONOMY', max_length=20, verbose_name='Clase')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CHECKED_IN', 'Facturado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuestos')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de reserva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_bookings', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='flights.commercialflight')),
            ],
            options={
                'verbose_name': 'Reserva de vuelo comercial',
                'verbose_name_plural': 'Reservas de vuelos comerciales',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('document_type', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=50, verbose_name='Número de documento')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('seat_number', models.CharField(blank=True, max_length=10, verbose_name='Número de asiento')),
                ('has_checked_in', models.BooleanField(default=False, verbose_name='Ha hecho check-in')),
                ('special_assistance', models.BooleanField(default=False, verbose_name='Necesita asistencia especial')),
                ('special_meal', models.CharField(blank=True, max_length=100, verbose_name='Comida especial')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='flights.commercialbooking')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat', to='flights.passenger'),
        ),
    ]
